### ISSUE TITLE
Create draft database schema

### ISSUE THREAD

**Issue by Birchlera** [garethmarkel/FMloop#3]

**Comment by garethmarkel** [comment]
Here's the schema that I was working with before the call on SUnday: https://drive.google.com/file/d/1rjtuktAuUp08LbbRVauymEFmCXAcMf4g/view?usp=sharing
The driving force behind most of these table structures was just to write something out so I could practice working with databases and Node, though, so I wouldn't say it has any inherent value as a  structure
